name: NPC
description: Non playable characters, but they still walk and talk
author: StarTux
version: 0.1
api-version: 1.13
website: https://cavetale.com
main: com.cavetale.npc.NPCPlugin
depend: [PacketListenerApi]
softdepend: []
commands:
  npc:
    aliases: []
    description: npc
    permission: npc.npc
    usage: /<command>
permissions:
  npc.npc:
    description: use /npc
    default: op
